### ISSUE TITLE
iron-data-table not working

### ISSUE THREAD

**Issue by jamesr73** [wintersandroid/rebrickable-tool#1]
Thanks for a cool framework for extending rebrickable.com, just what I was looking for! 

I'm new to Polymer and I've been fighting with it for a few hours. Lists, e.g. Set List, were not rendering. With a bit of digging I could see that the _data was being retrieved correctly but couldn't figure out why the iron-data-table wasn't working (list-of-sets.html). I'm still uncertain why it doesn't render but I have worked around it by forcing bower to use:

```
"iron-data-table": "=1.0.0-beta1",
```

rather than:

```
"iron-data-table": "^1.0.0-beta1",
```

which had installed beta3. I guess I should raise an issue there but I'm not sure how to describe it in any meaningful way.

I'm looking forward to learning Polymer and making the most of the rebrickable.com API :-)

PS I'm running node 4.4.5 via nvm on OS X 10.11.4

**Comment by mwinters-stuff** [comment]
Ahh - yes, I have been trying to debug beta3 of iron-data-table, beta 1 does work.. I have been discussing with the iron-data-table creator.

Polymer is great..!

**Comment by jamesr73** [comment]
Cool. I'll keep playing.

**Comment by mwinters-stuff** [comment]
If you want, have a look at this jsbin, which replicates the error in the iron-data-table 
https://jsbin.com/suluyed/edit?html,output

**Comment by mwinters-stuff** [comment]
If you do a bower-update and make sure iron-list is version 1.3.3, it will all work properly!

**Comment by jamesr73** [comment]
Great. Thanks for the update. I've let this slip in the last few days. So much to learn!!
